= Entrypoint

The entrypoint is typically written in assembly. The minimal code, that is runnable
against QEMU, given the linker script, is as follows:

.Entrypont assembly code
[source,as]
----
.attribute arch, "rv64gc"
.option arch, -c
.section .init
.global  _start
_start:
    wfi
    j _start
----

[NOTE]
Instead of using `rv64gc` and disabling the c extension, `rv64g` could be used.
However, rustc does not support this configuration.

.Kernel entrypoint
Whe the _machine_ is powered on, and the code in DRAM is loaded, the CPU is not
sufficiently initialized to run istructions generated by a higher level
langauge. For example, these instructions typically rely on a stack pointer,
which is not setup yet.

Therefore, the first code to run must be written in assembly. It will take care
of a few essential tasks, such as setting up the stack and global pointer,
before calling a function written in a higher level langauge.

Depending on the langauge and its features, the current linker script
and entrypoint assembly may not be sufficient. For example, many langauges
require additional symbols to be provided by the linker, such as `.init_array`.
